import {transactionLocalDataSource} from '@/src/data/local/transactions/transactionLocalDataSource';
import {now} from '@/src/core/date/now';

export async function seedTransactions2026() {
  await transactionLocalDataSource.insertMany([
    // January 2026
    {
      id: 'txn_2026_01_salary',
      type: 'income',
      amount: 1850000,
      currency: 'ARS',
      amount_in_main_currency: 1850000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-01-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_supermarket_01',
      type: 'expense',
      amount: 86500,
      currency: 'ARS',
      amount_in_main_currency: 86500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-01-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_food_01',
      type: 'expense',
      amount: 18200,
      currency: 'ARS',
      amount_in_main_currency: 18200,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-01-09T21:00:00.000Z',
      note: 'Dinner',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_house',
      type: 'expense',
      amount: 145000,
      currency: 'ARS',
      amount_in_main_currency: 145000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-01-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_transport',
      type: 'expense',
      amount: 21500,
      currency: 'ARS',
      amount_in_main_currency: 21500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-01-14T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_car',
      type: 'expense',
      amount: 98000,
      currency: 'ARS',
      amount_in_main_currency: 98000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_car',
      occurred_at: '2026-01-18T15:00:00.000Z',
      note: 'Car maintenance',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_usd_savings',
      type: 'income',
      amount: 150,
      currency: 'USD',
      amount_in_main_currency: 157500,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-01-20T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1050,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // February 2026
    {
      id: 'txn_2026_02_salary',
      type: 'income',
      amount: 1900000,
      currency: 'ARS',
      amount_in_main_currency: 1900000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-02-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_supermarket_01',
      type: 'expense',
      amount: 92400,
      currency: 'ARS',
      amount_in_main_currency: 92400,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-02-06T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_services',
      type: 'expense',
      amount: 76000,
      currency: 'ARS',
      amount_in_main_currency: 76000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-02-08T10:00:00.000Z',
      note: 'Services',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_food',
      type: 'expense',
      amount: 23600,
      currency: 'ARS',
      amount_in_main_currency: 23600,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-02-12T21:00:00.000Z',
      note: 'Restaurant',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_health',
      type: 'expense',
      amount: 64500,
      currency: 'ARS',
      amount_in_main_currency: 64500,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-02-17T13:15:00.000Z',
      note: 'Health',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_shopping',
      type: 'expense',
      amount: 132000,
      currency: 'ARS',
      amount_in_main_currency: 132000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-02-22T17:45:00.000Z',
      note: 'Shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // March 2026
    {
      id: 'txn_2026_03_salary',
      type: 'income',
      amount: 1950000,
      currency: 'ARS',
      amount_in_main_currency: 1950000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-03-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_supermarket',
      type: 'expense',
      amount: 101000,
      currency: 'ARS',
      amount_in_main_currency: 101000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-03-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_transport',
      type: 'expense',
      amount: 27500,
      currency: 'ARS',
      amount_in_main_currency: 27500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-03-08T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_house',
      type: 'expense',
      amount: 168000,
      currency: 'ARS',
      amount_in_main_currency: 168000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-03-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_car',
      type: 'expense',
      amount: 117000,
      currency: 'ARS',
      amount_in_main_currency: 117000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_car',
      occurred_at: '2026-03-18T15:00:00.000Z',
      note: 'Fuel and car',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_usd_travel',
      type: 'expense',
      amount: 90,
      currency: 'USD',
      amount_in_main_currency: 99000,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_travel',
      occurred_at: '2026-03-24T16:00:00.000Z',
      note: 'Travel USD',
      exchange_rate_to_main_currency: 1100,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // April 2026
    {
      id: 'txn_2026_04_salary',
      type: 'income',
      amount: 2050000,
      currency: 'ARS',
      amount_in_main_currency: 2050000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-04-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_supermarket',
      type: 'expense',
      amount: 112000,
      currency: 'ARS',
      amount_in_main_currency: 112000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-04-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_food',
      type: 'expense',
      amount: 28500,
      currency: 'ARS',
      amount_in_main_currency: 28500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-04-11T21:00:00.000Z',
      note: 'Food',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_services',
      type: 'expense',
      amount: 89500,
      currency: 'ARS',
      amount_in_main_currency: 89500,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-04-12T10:00:00.000Z',
      note: 'Services',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_shopping',
      type: 'expense',
      amount: 154000,
      currency: 'ARS',
      amount_in_main_currency: 154000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-04-19T17:45:00.000Z',
      note: 'Shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_extra_income',
      type: 'income',
      amount: 135000,
      currency: 'ARS',
      amount_in_main_currency: 135000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_earnings',
      occurred_at: '2026-04-26T12:00:00.000Z',
      note: 'Extra income',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // May 2026
    {
      id: 'txn_2026_05_salary',
      type: 'income',
      amount: 2150000,
      currency: 'ARS',
      amount_in_main_currency: 2150000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-05-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_supermarket',
      type: 'expense',
      amount: 121000,
      currency: 'ARS',
      amount_in_main_currency: 121000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-05-06T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_house',
      type: 'expense',
      amount: 188000,
      currency: 'ARS',
      amount_in_main_currency: 188000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-05-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_transport',
      type: 'expense',
      amount: 31500,
      currency: 'ARS',
      amount_in_main_currency: 31500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-05-14T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_health',
      type: 'expense',
      amount: 79000,
      currency: 'ARS',
      amount_in_main_currency: 79000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-05-18T13:15:00.000Z',
      note: 'Health',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_usd_savings',
      type: 'income',
      amount: 200,
      currency: 'USD',
      amount_in_main_currency: 230000,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-05-22T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1150,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // June 2026
    {
      id: 'txn_2026_06_salary',
      type: 'income',
      amount: 2250000,
      currency: 'ARS',
      amount_in_main_currency: 2250000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-06-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_06_supermarket',
      type: 'expense',
      amount: 132000,
      currency: 'ARS',
      amount_in_main_currency: 132000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-06-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_06_car',
      type: 'expense',
      amount: 141000,
      currency: 'ARS',
      amount_in_main_currency: 141000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_car',
      occurred_at: '2026-06-15T15:00:00.000Z',
      note: 'Car',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_06_food',
      type: 'expense',
      amount: 34200,
      currency: 'ARS',
      amount_in_main_currency: 34200,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-06-18T21:00:00.000Z',
      note: 'Restaurant',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_06_travel',
      type: 'expense',
      amount: 260000,
      currency: 'ARS',
      amount_in_main_currency: 260000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_travel',
      occurred_at: '2026-06-24T16:00:00.000Z',
      note: 'Travel',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // July 2026
    {
      id: 'txn_2026_07_salary',
      type: 'income',
      amount: 2350000,
      currency: 'ARS',
      amount_in_main_currency: 2350000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-07-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_07_supermarket',
      type: 'expense',
      amount: 143000,
      currency: 'ARS',
      amount_in_main_currency: 143000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-07-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_07_house',
      type: 'expense',
      amount: 215000,
      currency: 'ARS',
      amount_in_main_currency: 215000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-07-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_07_shopping',
      type: 'expense',
      amount: 194000,
      currency: 'ARS',
      amount_in_main_currency: 194000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-07-20T17:45:00.000Z',
      note: 'Shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_07_usd_travel',
      type: 'expense',
      amount: 120,
      currency: 'USD',
      amount_in_main_currency: 144000,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_travel',
      occurred_at: '2026-07-25T16:00:00.000Z',
      note: 'Travel USD',
      exchange_rate_to_main_currency: 1200,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // August 2026
    {
      id: 'txn_2026_08_salary',
      type: 'income',
      amount: 2450000,
      currency: 'ARS',
      amount_in_main_currency: 2450000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-08-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_08_supermarket',
      type: 'expense',
      amount: 155000,
      currency: 'ARS',
      amount_in_main_currency: 155000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-08-06T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_08_services',
      type: 'expense',
      amount: 110000,
      currency: 'ARS',
      amount_in_main_currency: 110000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-08-12T10:00:00.000Z',
      note: 'Services',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_08_transport',
      type: 'expense',
      amount: 38500,
      currency: 'ARS',
      amount_in_main_currency: 38500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-08-14T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_08_health',
      type: 'expense',
      amount: 98000,
      currency: 'ARS',
      amount_in_main_currency: 98000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-08-22T13:15:00.000Z',
      note: 'Health',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // September 2026
    {
      id: 'txn_2026_09_salary',
      type: 'income',
      amount: 2550000,
      currency: 'ARS',
      amount_in_main_currency: 2550000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-09-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_09_supermarket',
      type: 'expense',
      amount: 168000,
      currency: 'ARS',
      amount_in_main_currency: 168000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-09-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_09_house',
      type: 'expense',
      amount: 240000,
      currency: 'ARS',
      amount_in_main_currency: 240000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-09-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_09_car',
      type: 'expense',
      amount: 172000,
      currency: 'ARS',
      amount_in_main_currency: 172000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_car',
      occurred_at: '2026-09-18T15:00:00.000Z',
      note: 'Car',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_09_usd_savings',
      type: 'income',
      amount: 180,
      currency: 'USD',
      amount_in_main_currency: 226800,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-09-22T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1260,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // October 2026
    {
      id: 'txn_2026_10_salary',
      type: 'income',
      amount: 2650000,
      currency: 'ARS',
      amount_in_main_currency: 2650000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-10-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_10_supermarket',
      type: 'expense',
      amount: 181000,
      currency: 'ARS',
      amount_in_main_currency: 181000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-10-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_10_food',
      type: 'expense',
      amount: 46500,
      currency: 'ARS',
      amount_in_main_currency: 46500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-10-12T21:00:00.000Z',
      note: 'Restaurant',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_10_shopping',
      type: 'expense',
      amount: 225000,
      currency: 'ARS',
      amount_in_main_currency: 225000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-10-21T17:45:00.000Z',
      note: 'Shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_10_travel',
      type: 'expense',
      amount: 310000,
      currency: 'ARS',
      amount_in_main_currency: 310000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_travel',
      occurred_at: '2026-10-26T16:00:00.000Z',
      note: 'Travel',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // November 2026
    {
      id: 'txn_2026_11_salary',
      type: 'income',
      amount: 2750000,
      currency: 'ARS',
      amount_in_main_currency: 2750000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-11-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_11_supermarket',
      type: 'expense',
      amount: 194000,
      currency: 'ARS',
      amount_in_main_currency: 194000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-11-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_11_services',
      type: 'expense',
      amount: 132000,
      currency: 'ARS',
      amount_in_main_currency: 132000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-11-12T10:00:00.000Z',
      note: 'Services',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_11_health',
      type: 'expense',
      amount: 116000,
      currency: 'ARS',
      amount_in_main_currency: 116000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-11-19T13:15:00.000Z',
      note: 'Health',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_11_usd_travel',
      type: 'expense',
      amount: 160,
      currency: 'USD',
      amount_in_main_currency: 211200,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_travel',
      occurred_at: '2026-11-24T16:00:00.000Z',
      note: 'Travel USD',
      exchange_rate_to_main_currency: 1320,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // December 2026
    {
      id: 'txn_2026_12_salary',
      type: 'income',
      amount: 2900000,
      currency: 'ARS',
      amount_in_main_currency: 2900000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-12-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_12_supermarket',
      type: 'expense',
      amount: 215000,
      currency: 'ARS',
      amount_in_main_currency: 215000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-12-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_12_house',
      type: 'expense',
      amount: 280000,
      currency: 'ARS',
      amount_in_main_currency: 280000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-12-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_12_shopping',
      type: 'expense',
      amount: 340000,
      currency: 'ARS',
      amount_in_main_currency: 340000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-12-20T17:45:00.000Z',
      note: 'Christmas shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_12_extra_income',
      type: 'income',
      amount: 350000,
      currency: 'ARS',
      amount_in_main_currency: 350000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_earnings',
      occurred_at: '2026-12-22T12:00:00.000Z',
      note: 'Year end bonus',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_12_usd_savings',
      type: 'income',
      amount: 250,
      currency: 'USD',
      amount_in_main_currency: 337500,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-12-27T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1350,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
  ]);
}
