import {categoryLocalDataSource} from '@/src/data/local/categories/categoryLocalDataSource';
import {now} from '@/src/core/date/now';

export async function seedDefaultCategories() {
  const count = await categoryLocalDataSource.count();

  if (count > 0) return;

  await categoryLocalDataSource.insertMany([
    // Expenses
    {
      id: 'cat_food',
      name: 'Food',
      type: 'expense',
      icon: 'food',
      color: '#22C55E',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_supermarket',
      name: 'Supermarket',
      type: 'expense',
      icon: 'store',
      color: '#16A34A',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_house',
      name: 'House',
      type: 'expense',
      icon: 'home',
      color: '#F59E0B',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_transport',
      name: 'Transport',
      type: 'expense',
      icon: 'bus',
      color: '#3B82F6',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_car',
      name: 'Car',
      type: 'expense',
      icon: 'car',
      color: '#2563EB',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_eating_out',
      name: 'Eating out',
      type: 'expense',
      icon: 'silverware-fork-knife',
      color: '#EF4444',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_entertainment',
      name: 'Entertainment',
      type: 'expense',
      icon: 'movie',
      color: '#A855F7',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_health',
      name: 'Health',
      type: 'expense',
      icon: 'hospital',
      color: '#EC4899',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_services',
      name: 'Services',
      type: 'expense',
      icon: 'tools',
      color: '#64748B',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_travel',
      name: 'Travel',
      type: 'expense',
      icon: 'map',
      color: '#06B6D4',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // Income
    {
      id: 'cat_salary',
      name: 'Salary',
      type: 'income',
      icon: 'salary',
      color: '#10B981',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_savings',
      name: 'Savings',
      type: 'income',
      icon: 'savings',
      color: '#84CC16',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_deposits',
      name: 'Deposits',
      type: 'income',
      icon: 'deposit',
      color: '#14B8A6',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_daily_performance',
      name: 'Daily performance',
      type: 'income',
      icon: 'performance',
      color: '#0EA5E9',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_earnings',
      name: 'Earnings',
      type: 'income',
      icon: 'earnings',
      color: '#6366F1',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
  ]);
}
